services:
  spaceport_alpha:
    image: hub.66bit.ru/shared/images/devops-practice:latest
    ports:
      - 8000:80
    environment:
      - ASP_INSTANCE_NAME=alpha
    networks:
      - spacehub_network

  spaceport_beta:
    image: hub.66bit.ru/shared/images/devops-practice:latest
    ports:
      - 8001:80
    environment:
      - ASP_INSTANCE_NAME=beta
    networks:
      - spacehub_network
 
  spaceport_gamma:
    image: hub.66bit.ru/shared/images/devops-practice:latest
    ports:
      - 8002:80
    environment:
      - ASP_INSTANCE_NAME=gamma
    networks:
      - spacehub_network

  spaceport_delta:
    image: hub.66bit.ru/shared/images/devops-practice:latest
    ports:
      - 8003:80
    environment:
      - ASP_INSTANCE_NAME=delta
    networks:
      - spacehub_network
  
  dispatcher:
    image: nginx:1.29.0
    volumes:
      - .templates:/etc/nginx/templates
    ports: 
      - 80:80
    environment:
      - NGINX_HOST=spacehub.local
      - NGINX_PORT=80
      - SPACEPORT1_SERVICE_HOST=spaceport_alpha
      - SPACEPORT2_SERVICE_HOST=spaceport_beta
      - SPACEPORT3_SERVICE_HOST=spaceport_gamma
      - SPACEPORT4_SERVICE_HOST=spaceport_delta
    networks:
      - spacehub_network
    depends_on:
      - spaceport_alpha
      - spaceport_beta
      - spaceport_gamma
      - spaceport_delta

networks:
  spacehub_network: 
    driver: bridge
